version: "3.8"

services:
  user_db:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$USER_DB_PASSWORD
    ports:
      - $USER_DB_LOCAL_PORT:$USER_DB_DOCKER_PORT
    volumes:
      - user_db:/data/db

  destination_db:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DESTINATION_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DESTINATION_DB_PASSWORD
    ports:
      - $DESTINATION_DB_LOCAL_PORT:$DESTINATION_DB_DOCKER_PORT
    volumes:
      - destination_db:/data/db
        
  user_db_adapter:
    depends_on:
      - user_db
    build: ./adapter_services/user_db_adapter
    restart: always
    env_file: ./.env
    ports:
      - $USER_DB_ADAPTER_LOCAL_PORT:$USER_DB_ADAPTER_DOCKER_PORT
    environment:
      - DB_HOST=user_db
      - DB_USER=$USER_DB_USER
      - DB_PASSWORD=$USER_DB_PASSWORD
      - DB_NAME=$USER_DB_DATABASE
      - DB_PORT=$USER_DB_DOCKER_PORT
    stdin_open: true
    tty: true

  destination_db_adapter:
    depends_on:
      - destination_db
    build: ./adapter_services/destination_db_adapter
    restart: always
    env_file: ./.env
    ports:
      - $DESTINATION_DB_ADAPTER_LOCAL_PORT:$DESTINATION_DB_ADAPTER_DOCKER_PORT
    environment:
      - DB_HOST=destination_db
      - DB_USER=$DESTINATION_DB_USER
      - DB_PASSWORD=$DESTINATION_DB_PASSWORD
      - DB_NAME=$DESTINATION_DB_DATABASE
      - DB_PORT=$DESTINATION_DB_DOCKER_PORT
    stdin_open: true
    tty: true

  forecast_api_adapter:
    build: ./adapter_services/forecast_api_adapter
    restart: always
    env_file: ./.env
    ports:
      - $FORECAST_API_ADAPTER_LOCAL_PORT:$FORECAST_API_ADAPTER_DOCKER_PORT
    environment:
      - API_KEY=$FORECAST_API_KEY
      - NODE_ENV=production
    stdin_open: true
    tty: true
  
  geocoding_api_adapter:
    build: ./adapter_services/geocoding_api_adapter
    restart: always
    env_file: ./.env
    ports:
      - $GEOCODING_API_ADAPTER_LOCAL_PORT:$GEOCODING_API_ADAPTER_DOCKER_PORT
    stdin_open: true
    tty: true

  crowd_api_adapter:
    build: ./adapter_services/crowd_api_adapter
    restart: always
    env_file: ./.env
    ports:
      - $CROWD_API_ADAPTER_LOCAL_PORT:$CROWD_API_ADAPTER_DOCKER_PORT
    environment:
      - API_KEY=$TOMTOM_API_KEY
    stdin_open: true
    tty: true
  
  range_api_adapter:
    build: ./adapter_services/range_api_adapter
    restart: always
    env_file: ./.env
    ports:
      - $RANGE_API_ADAPTER_LOCAL_PORT:$RANGE_API_ADAPTER_DOCKER_PORT
    environment:
      - API_KEY=$TOMTOM_API_KEY
    stdin_open: true
    tty: true

  emailrep_api_adapter:
    build: ./adapter_services/emailrep_api_adapter
    restart: always
    env_file: ./.env
    ports:
      - $EMAILREP_API_ADAPTER_LOCAL_PORT:$EMAILREP_API_ADAPTER_DOCKER_PORT
    stdin_open: true
    tty: true

  coordinates_service:
    build: ./business_logic_services/coordinates_service
    restart: always
    env_file: ./.env
    ports:
      - $COORDINATES_SERVICE_LOCAL_PORT:$COORDINATES_SERVICE_DOCKER_PORT
    environment:
      - COORDINATES_SERVICE_DOCKER_PORT=$COORDINATES_SERVICE_DOCKER_PORT
    stdin_open: true
    tty: true

  reachable_destinations_service:
    build: ./business_logic_services/reachable_destinations_service
    restart: always
    env_file: ./.env
    ports:
      - $REACHABLE_DESTINATIONS_SERVICE_LOCAL_PORT:$REACHABLE_DESTINATIONS_SERVICE_DOCKER_PORT
    environment:
      - REACHABLE_DESTINATIONS_SERVICE_DOCKER_PORT=$REACHABLE_DESTINATIONS_SERVICE_DOCKER_PORT
    stdin_open: true
    tty: true

  coordinates_rating_service:
    build: ./business_logic_services/coordinates_rating_service
    restart: always
    env_file: ./.env
    ports:
      - $COORDINATES_RATING_SERVICE_LOCAL_PORT:$COORDINATES_RATING_SERVICE_DOCKER_PORT
    stdin_open: true
    tty: true

  best_destinations_service:
    build: ./process_centric_services/best_destinations_service
    restart: always
    env_file: ./.env
    ports:
      - $BEST_DESTINATIONS_SERVICE_LOCAL_PORT:$BEST_DESTINATIONS_SERVICE_DOCKER_PORT
    stdin_open: true
    tty: true
  
  frontend:
    build: ./frontend
    restart: always
    env_file: ./.env
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    stdin_open: true
    tty: true
    
volumes:
  user_db:
  destination_db:
