version: "3.8"
services:
  user_db:
    image: mongo:5.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${UDU}
      - MONGO_INITDB_ROOT_PASSWORD=${UDP}
    ports:
      - 7017:27017
    volumes:
      -  ${WEBAPP_STORAGE_HOME}/userdb:/data/db
  destination_db:
    image: mongo:5.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DDU}
      - MONGO_INITDB_ROOT_PASSWORD=${DDP}
    ports:
      - 7018:27017
    volumes:
      -  ${WEBAPP_STORAGE_HOME}/destinationdb:/data/db
  destination_db_adapter:
    image: daytripacr.azurecr.io/destination_db_adapter:latest
    ports:
      - 6869:8080
    environment:
      - DB_HOST=${DDD}
      - DB_USER=${DDU}
      - DB_PASSWORD=${DDP}
      - DB_NAME=${DDD}
      - DB_PORT=${DDDP}
  user_db_adapter:
    image: daytripacr.azurecr.io/user_db_adapter:latest
    ports:
      - 6868:8080
    environment:
      - DB_HOST=${UDD}
      - DB_USER=${UDU}
      - DB_PASSWORD=${UDP}
      - DB_NAME=${UDD}
      - DB_PORT=${UDDP}
  forecast_api_adapter:
    image: daytripacr.azurecr.io/forecast_api_adapter:latest
    ports:
      - 6870:8080
    environment:
      - API_KEY=${FAK}
      - NODE_ENV=${NE}
  geocoding_api_adapter:
    image: daytripacr.azurecr.io/geocoding_api_adapter:latest
    ports:
      - 6871:8080
  crowd_api_adapter:
    image: daytripacr.azurecr.io/crowd_api_adapter:latest
    ports:
      - 6872:8080
    environment:
      - API_KEY=${TAK}
  range_api_adapter:
    image: daytripacr.azurecr.io/range_api_adapter:latest
    ports:
      - 6873:8080
    environment:
      - API_KEY=${TAK}
  emailcheck_api_adapter:
    image: daytripacr.azurecr.io/emailcheck_api_adapter:latest
    ports:
      - 6874:8080
  ip_api_adapter:
    image: daytripacr.azurecr.io/ip_api_adapter:latest
    ports:
      - 6875:8080
  air_pollution_api_adapter:
    image: daytripacr.azurecr.io/air_pollution_api_adapter:latest
    ports:
      - 6876:8080
  coordinates_service:
    image: daytripacr.azurecr.io/coordinates_service:latest
    ports:
      - 6877:8080
  reachable_destinations_service:
    image: daytripacr.azurecr.io/reachable_destinations_service:latest
    ports:
      - 6878:8080
  coordinates_rating_service:
    image: daytripacr.azurecr.io/coordinates_rating_service:latest
    ports:
      - 6879:8080
  best_destinations_service:
    image: daytripacr.azurecr.io/best_destinations_service:latest
    ports:
      - 6881:8080
  user_login_service:
    image: daytripacr.azurecr.io/user_login_service:latest
    ports:
      - 6882:8080
  user_registration_service:
    image: daytripacr.azurecr.io/user_registration_service:latest
    ports:
      - 6883:8080
  valid_email_service:
    image: daytripacr.azurecr.io/valid_email_service:latest
    ports:
      - 6880:8080
  frontend:
    image: daytripacr.azurecr.io/frontend:latest
    ports:
      - 80:80