version: '3.8'

services:
  user_db_adapter:
    depends_on:
      - user_db
    build: ./user_db_adapter
    restart: always
    env_file: ./.env
    ports:
      - $USER_DB_ADAPTER_LOCAL_PORT:$USER_DB_ADAPTER_DOCKER_PORT
    environment:
      - DB_HOST=user_db
      - DB_USER=$USER_DB_USER
      - DB_PASSWORD=$USER_DB_PASSWORD
      - DB_NAME=$USER_DB_NAME
      - DB_PORT=$USER_DB_DOCKER_PORT
    stdin_open: true
    tty: true

  user_db:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$USER_DB_PASSWORD
    ports:
      - $USER_DB_LOCAL_PORT:$USER_DB_DOCKER_PORT
    volumes:
      - db:/data/db

volumes:
  db: